### ISSUE TITLE
A problem of de novo model

### ISSUE THREAD

**Issue by Biols0208** [Xingyu-Liao/LongRepMarker_v2.0#10]
Hi Dr. Liao,

When I tried de novo mode with the following command 
“java -Xmx10G LongRepMarker -N ./test.fq -k 49 -m 100 -t 10 -f ./GCF_000001735.4_TAIR10.1_genomic.fna -o ./results”,
I got an error message as follows:

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/50230939/195235559-580b71a5-9b80-467a-b8a8-879d9b3193ea.png">

I don't know how to solve this problem.
In addition, when I run the parameter mode, I have the correct output and no error is reported.

Best,
Lishuo

**Comment by Xingyu-Liao** [comment]
> Hi Dr. Liao,
> 
> When I tried de novo mode with the following command “java -Xmx10G LongRepMarker -N ./test.fq -k 49 -m 100 -t 10 -f ./GCF_000001735.4_TAIR10.1_genomic.fna -o ./results”, I got an error message as follows:
> 
> <img alt="image" width="1455" src="https://user-images.githubusercontent.com/50230939/195235559-580b71a5-9b80-467a-b8a8-879d9b3193ea.png">
> 
> I don't know how to solve this problem. In addition, when I run the parameter mode, I have the correct output and no error is reported.
> 
> Best, Lishuo

-----------------------------------

Dear Lishuo,

Thanks for your email. The de novo detection mode based on only third-generation sequencing reads is in the process of secondary development. Therefore, it cannot be used at this time. We apologize for the inconvenience caused by the upgrade.
By the way, the new version of the de novo detection mode based on only third-generation sequencing reads will be isolated from LongRepMarker and become a new tool with stronger functions and performance.  Thank you for your attention.

Best regards,


Xingyu Liao

**Comment by wq-ls** [comment]
> > Hi Dr. Liao,
> > When I tried de novo mode with the following command “java -Xmx10G LongRepMarker -N ./test.fq -k 49 -m 100 -t 10 -f ./GCF_000001735.4_TAIR10.1_genomic.fna -o ./results”, I got an error message as follows:
> > <img alt="image" width="1455" src="https://user-images.githubusercontent.com/50230939/195235559-580b71a5-9b80-467a-b8a8-879d9b3193ea.png">
> > I don't know how to solve this problem. In addition, when I run the parameter mode, I have the correct output and no error is reported.
> > Best, Lishuo
> 
> Dear Lishuo,
> 
> Thanks for your email. The de novo detection mode based on only third-generation sequencing reads is in the process of secondary development. Therefore, it cannot be used at this time. We apologize for the inconvenience caused by the upgrade. By the way, the new version of the de novo detection mode based on only third-generation sequencing reads will be isolated from LongRepMarker and become a new tool with stronger functions and performance. Thank you for your attention.
> 
> Best regards,
> 
> Xingyu Liao

**Comment by Biols0208** [comment]
Many thanks to Dr. Liao for your reply ！！！
I am very much looking forward to the release of your new tool ！！！
